// Knowledge Base Starter Kit — file contents
// Each file is a { path, content } pair that gets bundled into the download

export function generateKit(topic: string): { path: string; content: string }[] {
  return [
    {
      path: "README.md",
      content: `# ${topic} Knowledge Base

## What this is
A structured AI knowledge base system for **${topic}**. Drop this folder into any AI tool (Claude, ChatGPT, Cursor, etc.) and use the numbered prompts to build a wiki that compounds over time.

## How to use it

### First time setup (10 minutes)
1. Open your AI tool (Claude, ChatGPT, or any LLM with file access)
2. Point it at this folder or upload these files
3. Tell the AI: "Read CLAUDE.md and follow the instructions"

### Building your knowledge base
4. Add 3-5 source materials to the \`sources/\` folder (articles, notes, PDFs)
5. Run the prompts in the \`prompts/\` folder in order (01, 02, 03...)
6. Each prompt tells the AI what to do. Just copy-paste it into your AI chat.
7. Save the AI's output in the \`wiki/\` folder

### Growing it over time
- Add new sources whenever you find good material
- Run prompt 03 (compile article) for each new subtopic
- Run prompt 04 (cross-link) after adding new articles
- Run prompt 05 (find gaps) monthly to discover what's missing
- Run prompt 07 (quality check) before sharing with others

## Folder structure

\`\`\`
${topic.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-knowledge-base/
├── README.md              ← You are here
├── CLAUDE.md              ← The schema — give this to your AI first
├── prompts/               ← Run these in order to build your wiki
├── sources/               ← Your raw materials go here
│   ├── articles/          ← Published articles and blog posts
│   ├── notes/             ← Your personal notes
│   └── reference/         ← Official docs, specs, data
├── wiki/                  ← AI-generated articles land here
└── queries/               ← Questions you ask + answers you keep
\`\`\`

## Requirements
- Any AI assistant that can read files (Claude, ChatGPT, Gemini, etc.)
- A text editor or note-taking app (VS Code, Obsidian, Notion, even Notepad)
- No coding required. No terminal. No technical setup.

## Built with
Created by MrPrompts — https://mrprompts.ai
Learn more: https://mrprompts.ai/learn/ai-knowledge-base-guide
`,
    },
    {
      path: "CLAUDE.md",
      content: `# ${topic} Knowledge Base
# Version: 1.0
# Generated by MrPrompts — https://mrprompts.ai

## Purpose
A structured, interlinked knowledge base on ${topic}, compiled from curated sources and maintained with AI assistance.

## Structure
- /sources — Raw materials: articles, notes, and reference documents. NEVER modified by AI.
  - /sources/articles — Published articles, blog posts, and news
  - /sources/notes — Personal observations, meeting notes, ideas
  - /sources/reference — Official documentation, specs, research papers
- /wiki — Compiled, interlinked wiki articles. Generated and maintained by AI following this schema.
- /queries — Questions asked and answers generated. Good answers get promoted to wiki articles.
- /prompts — Prompt templates for building and maintaining the knowledge base.

## Article Format
Every wiki article MUST follow this structure:
1. **Title** as H1
2. **Summary** — 2-3 sentences explaining the concept (must stand alone)
3. **Body** — organized with H2 sections, each covering one aspect
4. **Key Takeaways** — 3-5 bullet points (the "so what")
5. **Sources** — list which /sources files informed this article
6. **Related** — [[wikilinks]] to connected articles in the wiki

## Taxonomy
Categories should be defined based on the natural structure of ${topic}.
Start with 4-6 top-level categories. Add more only when a category has 10+ articles.
Tags can overlap across categories. Use lowercase-with-hyphens for tag names.

## Naming Conventions
- Wiki articles: Title-Case-With-Hyphens.md (e.g., Chain-Of-Thought-Prompting.md)
- Source files: YYYY-MM-DD-Source-Title.md (e.g., 2026-04-09-Karpathy-Autoresearch.md)
- Query files: YYYY-MM-DD-Question-Topic.md

## Rules
1. NEVER modify files in /sources — they are read-only reference material
2. ALWAYS cite which source(s) informed each wiki article
3. Use [[wikilinks]] to connect related concepts — every article links to at least 2 others
4. One concept per page — if an article covers two distinct ideas, split it
5. Every factual claim must trace back to a source. If no source supports it, flag it as [UNVERIFIED]
6. When updating an article, add "Last updated: YYYY-MM-DD" at the bottom
7. New articles must link to at least 2 existing articles (prevents orphan pages)
8. Keep summaries self-contained — someone should understand the concept from the summary alone
9. Write for a knowledgeable non-expert. No unexplained jargon.
10. When in doubt, ask the user rather than guessing
`,
    },
    {
      path: "prompts/01-decompose-topic.md",
      content: `# Prompt 01: Decompose Topic

## When to use
Run this FIRST, before anything else. It breaks your topic into subtopics that become individual wiki articles.

## Instructions
Copy everything below the line into your AI chat. Make sure the AI has already read your CLAUDE.md file.

---

Read the CLAUDE.md schema in this knowledge base. My topic is "${topic}".

Break this topic into 8-12 subtopics that should each become a wiki article. For each subtopic:

1. **Article title** (following the naming convention in CLAUDE.md)
2. **One-sentence description** of what this article will cover
3. **Category** it belongs to
4. **Related subtopics** it should link to (at least 2)

Organize the subtopics from foundational (concepts a beginner needs first) to advanced (concepts that build on earlier ones).

After listing the subtopics, suggest 4-6 categories that naturally group them.

Output this as a structured list I can use as my build plan.
`,
    },
    {
      path: "prompts/02-research-questions.md",
      content: `# Prompt 02: Generate Research Questions

## When to use
After running Prompt 01. Use this to figure out what sources you need to find for each subtopic.

## Instructions
Copy everything below the line into your AI chat.

---

Here are the subtopics I plan to cover in my ${topic} knowledge base:

[PASTE YOUR SUBTOPIC LIST FROM PROMPT 01 HERE]

For each subtopic, generate:

1. **3 research questions** I should be able to answer with good sources
2. **What kind of source** would best answer each question (academic paper, blog post, official docs, case study, expert opinion)
3. **Search terms** I can use to find these sources (for Google, Perplexity, or Google Scholar)

Prioritize the subtopics: which ones should I research and write FIRST because other articles depend on them?
`,
    },
    {
      path: "prompts/03-compile-article.md",
      content: `# Prompt 03: Compile Wiki Article

## When to use
After you have added source materials to the /sources folder. Run this once for each subtopic/article you want to create.

## Instructions
Copy everything below the line into your AI chat. Replace [ARTICLE TOPIC] with the specific subtopic.

---

Read the CLAUDE.md schema for this knowledge base. Then read all files in the /sources folder.

Write a wiki article about [ARTICLE TOPIC] following the exact format specified in CLAUDE.md:

1. H1 title
2. 2-3 sentence summary that stands alone
3. Body with H2 sections
4. Key Takeaways (3-5 bullets)
5. Sources section citing which /sources files you drew from
6. Related section with [[wikilinks]] to other articles that exist or should exist

Rules:
- Only include information supported by the sources. If you need to include general knowledge, mark it as [GENERAL KNOWLEDGE] so I can verify or find a source.
- Write for a knowledgeable non-expert. Explain jargon when first used.
- One concept per article. If you find yourself covering two distinct ideas, tell me and suggest splitting into two articles.
- The summary must make sense to someone who reads ONLY the summary.

Save the output as /wiki/[Article-Title].md following the naming convention in CLAUDE.md.
`,
    },
    {
      path: "prompts/04-cross-link.md",
      content: `# Prompt 04: Cross-Link Articles

## When to use
After you have 5+ articles in the /wiki folder. This connects your articles into a real knowledge web.

## Instructions
Copy everything below the line into your AI chat.

---

Read all articles in the /wiki folder.

For each article:
1. Identify every concept mentioned that has its own article in the wiki
2. Add [[wikilinks]] to those articles where they are naturally referenced in the text
3. Make sure the Related section at the bottom includes all directly connected articles
4. If any article has fewer than 2 outgoing links, suggest where links should be added

Then create or update /wiki/_INDEX.md with:
- A table of contents listing every article, grouped by category
- Article count per category
- A list of any "orphan" articles (articles with no incoming links from other articles)

Do not modify the Sources sections. Only add links and update the index.
`,
    },
    {
      path: "prompts/05-find-gaps.md",
      content: `# Prompt 05: Find Gaps

## When to use
After you have built your initial set of articles. Run this monthly to discover what's missing.

## Instructions
Copy everything below the line into your AI chat.

---

Read the CLAUDE.md schema and all articles in /wiki.

Analyze the knowledge base for gaps:

1. **Missing subtopics**: What concepts are referenced in existing articles but don't have their own article yet? List them with a one-sentence description of what each article should cover.

2. **Thin articles**: Which existing articles are shorter than 500 words or only scratch the surface of their topic? List them with specific suggestions for what to add.

3. **Missing connections**: Which articles should be linked to each other but aren't? List the specific article pairs and why they should connect.

4. **Source gaps**: Which topics rely on general knowledge rather than cited sources? List them so I can find supporting sources.

5. **Category imbalance**: Are any categories significantly larger or smaller than others? Should any category be split or merged?

Prioritize the gaps: which ones should I fill first to make the knowledge base most useful?
`,
    },
    {
      path: "prompts/06-expand-article.md",
      content: `# Prompt 06: Expand Article

## When to use
When the gap analyzer (Prompt 05) identifies a thin article, or when you want to deepen a specific topic.

## Instructions
Copy everything below the line into your AI chat. Replace [ARTICLE] with the filename.

---

Read /wiki/[ARTICLE] and all files in /sources.

This article needs to be deeper. Expand it by:

1. Adding more detail to each existing section (aim for 200-400 words per H2 section)
2. Adding 1-2 new H2 sections that cover aspects of this topic not yet addressed
3. Including specific examples, comparisons, or case studies where relevant
4. Adding more [[wikilinks]] to related articles
5. Updating the Key Takeaways to reflect the new depth
6. Updating the Sources section if you drew from additional source files

Maintain the same article format from CLAUDE.md. Keep the writing style consistent with the existing text. Flag any claims that are not supported by the sources as [NEEDS SOURCE].
`,
    },
    {
      path: "prompts/07-quality-check.md",
      content: `# Prompt 07: Quality Check

## When to use
Before sharing your knowledge base with others, or quarterly as maintenance.

## Instructions
Copy everything below the line into your AI chat.

---

Read the CLAUDE.md schema and every article in /wiki.

Audit the knowledge base for quality:

1. **Format compliance**: Does every article follow the format specified in CLAUDE.md? (Title, summary, body, takeaways, sources, related.) Flag any deviations.

2. **Citation check**: Does every factual claim trace back to a cited source? Flag any unsupported claims.

3. **Consistency**: Are there any contradictions between articles? (Article A says X, Article B says Y about the same concept.)

4. **Link integrity**: Are there any broken [[wikilinks]] that point to articles that don't exist?

5. **Summary quality**: Can each summary stand alone? Would someone understand the concept from the summary without reading the full article?

6. **Freshness**: Are any articles likely outdated based on the source dates?

7. **Naming**: Do all filenames follow the naming convention in CLAUDE.md?

For each issue found, specify:
- Which article
- What the issue is
- How to fix it

Rate the overall knowledge base quality: Excellent / Good / Needs Work / Critical Issues.
`,
    },
    {
      path: "sources/_INSTRUCTIONS.md",
      content: `# Sources Folder

This is where your raw materials go. The AI reads these but NEVER modifies them.

## What to put here

### /sources/articles/
Published content from other people:
- Blog posts
- News articles
- Industry reports
- Newsletter issues

### /sources/notes/
Your own thinking:
- Meeting notes
- Personal observations
- Ideas and hypotheses
- Interview transcripts

### /sources/reference/
Official or authoritative material:
- Documentation
- Research papers
- Specifications
- Data and statistics

## How to add a source
1. Create a new .md file in the appropriate subfolder
2. Name it: YYYY-MM-DD-Source-Title.md (e.g., 2026-04-09-Karpathy-Autoresearch.md)
3. Paste the content
4. Add a header with: Title, Author, Date, URL (if applicable)

## Tips
- Quality over quantity. 5 excellent sources beat 50 mediocre ones.
- Include the FULL text, not just a summary or link
- One source per file
- Add sources before running the article compilation prompts
`,
    },
    {
      path: "sources/articles/.gitkeep",
      content: "",
    },
    {
      path: "sources/notes/.gitkeep",
      content: "",
    },
    {
      path: "sources/reference/.gitkeep",
      content: "",
    },
    {
      path: "wiki/_INDEX.md",
      content: `# ${topic} — Wiki Index

This index is automatically updated when you run Prompt 04 (Cross-Link).

## Articles
(No articles yet. Run the prompts in /prompts to start building.)

## Categories
(Categories will be defined after you run Prompt 01.)

---
*Generated by MrPrompts — https://mrprompts.ai*
`,
    },
    {
      path: "queries/_INSTRUCTIONS.md",
      content: `# Queries Folder

This is where you save questions and answers.

## How it works
1. Ask your AI a question about your wiki topic
2. Tell it to read the /wiki articles first (not the raw sources)
3. If the answer is good, save it here as: YYYY-MM-DD-Question-Topic.md
4. Good answers can later be promoted to full wiki articles

## Example query format

\`\`\`markdown
# What are the main approaches to [topic]?
**Date:** 2026-04-09
**Based on:** wiki articles [list which ones the AI referenced]

## Answer
[The AI's synthesized answer]

## Follow-up questions
- [Questions this answer raised]
\`\`\`

## Why this matters
Every good query-answer pair enriches your knowledge base. Over time, the queries folder becomes a record of what you've learned and what questions led to deeper understanding.
`,
    },
  ];
}
